Description: |
  DeVesco Pierre
  Create S3 bucket for the Jenkins Final Project
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Jenkins Test

  VpcCIDR: 
    Description: The IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1CIDR: 
    Description: The IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 172.31.1.0/24

  InternetCIDR:
    Description: The CIRD notation for the internet
    Type: String
    Default: 0.0.0.0/0

  EC2InstanceName:
    Description: The AWS EC2 name used for tracking in the Instance Console
    Type: String
    Default: Jenkins
  
  AmazonAMI:
    Description: The unique ID of the Amazon Machine Image. Defaults to Free Amazon Linux Server.
    Type: String
    Default: ami-0a243dbef00e96192

  EC2KeyName:
    Description: The name of the EC2 Key pair
    Type: String

  EC2InstanceType:
    Description: The instance type of the EC2 instance, type list available in the Amazon EC2 User Guide for Linux Instances
    Type: String
    Default: t2.micro
  
  SSHIPAddress:
    Description: The CIRD notation for the internet address that will be used for SSH Access. Defaults to the Internet
    Type: String
    Default: 0.0.0.0/0

Resources:
  #  S3 Bucket
  JenkinsS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties: 
      BucketName: udacity-jenkins-s3-project
      PublicAccessBlockConfiguration:
        BlockPublicAcls: FALSE
        BlockPublicPolicy: FALSE
        IgnorePublicAcls: FALSE
        RestrictPublicBuckets: FALSE
      WebsiteConfiguration:
        IndexDocument: index.html

  JenkinsS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref JenkinsS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Sid: PublicReadGetObject
          Effect: Allow
          Principal: '*'
          Action: 
            - s3:GetObject
          Resource: !Join [ '', [!GetAtt JenkinsS3Bucket.Arn,'/*' ] ]

Outputs:
  S3URL: 
    Description: The Amazon S3 website endpoint for the specified bucket
    Value: !GetAtt JenkinsS3Bucket.WebsiteURL
    Export:
      Name: Jenkins-S3-URL